language: node_js
node_js:
  - 15.5.0

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn lint
  - yarn test --coverage
  - bash <(curl -s https://codecov.io/bash)
  - yarn build

deploy:
  - provider: script
    script: yarn semantic-release
    skip_cleanup: true
    on:
      branch: master

cache:
  yarn: true
